### ISSUE TITLE
strange output

### ISSUE THREAD

**Issue by shinnlu** [cascornelissen/svg-spritemap-webpack-plugin#104]
i have problem with output svg file.
![image](https://user-images.githubusercontent.com/570246/75225969-7c6f8780-57e6-11ea-9964-6358ff66d596.png)
upper line is single svg file with html:
`<img src="/front/images/svg/search.svg">`
lower is svg sprite file:
```
<svg>
<use xlink:href="/front/images/sprite.svg#sprite-search"></use>
</svg>
```
please tell me how to fix this.

webpack.mix.js
```
let mix = require('laravel-mix');
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');
const svgSourcePath = 'resources/assets/front/images/svg/*.svg';
const svgSpriteDestination= '/front/images/sprite.svg';
mix.webpackConfig({
    plugins: [
        new SVGSpritemapPlugin(
            svgSourcePath, {
                output: {
                    filename: svgSpriteDestination//,
                    // svgo: true
                }
            }
        )
    ]
})
```

package.json
```
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "font-awesome": "^4.5.0",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-vue-2": "^0.3.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.17.5",
    "moment": "^2.24.0",
    "moment-duration-format": "^1.3.0",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3"
  },
  "dependencies": {
    "currencyformatter.js": "^2.2.0",
    "laravel-mix": "^5.0.0",
    "svg-spritemap-webpack-plugin": "^3.5.4",
    "svgo": "^1.3.2",
    "swiper": "^5.2.0"
  }
```

**Comment by cascornelissen** [comment]
I'd guess/hope this is caused by SVGO which tries to optimize the SVGs for you, does the same happen when specifically setting `output.svgo` to `false` (it's `true` by default).

If that doesn't solve it, could you provide a small reproduction repository or zip file with just a couple of icons and a bare `webpack.config.js` I can use to reproduce the issue?

**Comment by shinnlu** [comment]
i think i may find the problem.
i was draw the svg with online editor before: https://vectr.com/
after i re-draw it with Inkscape and do svg sprite again, it's working good.

**Comment by cascornelissen** [comment]
Alright, thanks for sharing your solution!
