### ISSUE TITLE
scss formatter strips mandatory attributes from svg root

### ISSUE THREAD

**Issue by fgiust** [cascornelissen/svg-spritemap-webpack-plugin#105]
When generating a scss stylesheet the plugins remove any attribute from the svg root elements, breaking the rendering of many svgs.
As an example, starting from the following svg:

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ee203c" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  <rect x="3" y="3" width="7" height="7"></rect>
  <rect x="14" y="3" width="7" height="7"></rect>
  <rect x="14" y="14" width="7" height="7"></rect>
  <rect x="3" y="14" width="7" height="7"></rect>
</svg>

the root element gets changed to
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">

resulting in a totally transparent svg. For other sprites that declares fill="none" I am also getting additional black fills when this attribute gets removed

the attached patch adds cloning of root attributes to generated svgs:

[svg-spritemap-webpack-plugin+3.5.4.txt](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/4262249/svg-spritemap-webpack-plugin%2B3.5.4.txt)

.

**Comment by cascornelissen** [comment]
@fgiust, some of the (I guess) images in your description are missing. Could you fix those so that I can see what the problem is?
