### ISSUE TITLE
Ignoring input path

### ISSUE THREAD

**Issue by matthewlukedesign** [cascornelissen/svg-spritemap-webpack-plugin#109]
Hi I'm getting '94% asset optimizationTypeError: Cannot read property 'length' of undefined' after using this plugin.

Looks like it's ignoring my input path as it's logging a load of files it's trying to sprite outside of the dir I specified.

I'm using v1.0.0 as am using Webpack ~3. Any ideas?

Have tried a whole host of arguments, but here is my plugin at the moment (debugging by moving the icons folder next to webpack config but still not working and traversing the entire directory)

`new SVGSpritemapPlugin('icons/*.svg'),`

**Comment by cascornelissen** [comment]
You'd have to look at the documentation for `1.x` as well then, which can be found here: https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/v1.2.0.

It's been a while since I wrote that but I think this should work.

```
new SVGSpritemapPlugin({
    src: 'icons/*.svg'
})
```

**Comment by matthewlukedesign** [comment]
That's great, thanks so much - was wondering where I could find those docs.

**Comment by cascornelissen** [comment]
No problem at all, I'm guessing that solved it so I'm closing this issue. Feel free to comment if you have any other problems!
