### ISSUE TITLE
Add folder names to sprite id.

### ISSUE THREAD

**Issue by n1kk** [cascornelissen/svg-spritemap-webpack-plugin#111]
Is there a way to add folder names to sprite ids?

So given glob `icons/**/*.svg` and this structure 
```
icons/
  light-theme/
    icon-a.svg
  dark-theme/
    icon-a.svg
```
Right now i get duplicating ids as
```
prefix-icon-a
prefix-icon-a
```
I want to get ids like
```
prefix-light-theme-icon-a
prefix-dark-theme-icon-a
```

Maybe a good idea is to pass full path name to `sprite.idify` function ?

Then it ca be done as
```js
(filepath) => {
  const iconsDir = path.resolve(__dirname, "assets", "icons")
  return filepath.replace(iconsDir , "").replace(/[\s\/]+/g, '-');
}
```

**Comment by cascornelissen** [comment]
I'd be interested in adding a feature like this if there's a need for this. Going by the example code you've posted it might be easier to just add two separate plugin instances with different globs/paths in your Webpack configuration instead?

**Comment by n1kk** [comment]
For that small example sure, but I have a huge icon library with many folders, I have icons for multiple themes and for multiple devices like gamepads, for different modes, etc. There's way around that sure, I can run a script to copy them in one folder and rename before every build, I can add a new plugin for every folder there is with a script, but just seems like changing that function would be the cleanest solution.

To not break compatibility it can accept a second argument with full path or relative dir path only.

**Comment by cascornelissen** [comment]
I was just thinking, if you're just talking about the prefix for the sprite; it's already possible to customize this with a function that receives the full path to the current sprite as the first argument with the [`sprite.prefix`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#spriteprefix--sprite-) option.
