### ISSUE TITLE
A way to tap in svg and css generation

### ISSUE THREAD

**Issue by n1kk** [cascornelissen/svg-spritemap-webpack-plugin#112]
I have a lot of icons and not all of them are the same size and not all are squared, so I need two things, 
- some icons need to be centered in the square because software that exports them cuts off white space
- other icons are just double wide so I need to create a custom css for them to maintain their aspect ratio

It would be great if there was a function that I could create to tap into the generation of svg to center icons view boxes, and another to tap into css so I could create custom css for them.

**Comment by cascornelissen** [comment]
I'm not sure if that would be something this plugin should cover but then again if it's just two options that optionally implement a function 🤷‍♂️ Rou're free to submit a PR so that we have some code/implementation details to talk about.
