### ISSUE TITLE
After adding an SVG in the src folder,  the sprite generated is empty.

### ISSUE THREAD

**Issue by stereochuck** [cascornelissen/svg-spritemap-webpack-plugin#113]
I had this issue two times since a week. Occur on Linux and OSX.

Everything worked great, i had around 20 icons in my sprite and after adding  a random svg to the src folder (copy/pasting or create new empty one in atom) the sprite only return an empty svg tag.

After this error I can't regenerate the sprite. I tried, deleting svg and adding them back one by one, changing plugin setting, rm -rf node module, installing everything again and the sprite is always empty. No error in terminal.

Sprite,svg is only containing this : 
`<svg xmlns="http://www.w3.org/2000/svg"/>`

Here my code :
`
 mix.webpackConfig( {

        plugins: [

            new SVGSpritemapPlugin('${PATHS.src}/sprite/*.svg',

            {

                output: {

                    filename: '${PATHS.dist}/img/sprite.svg',

                    svg4everybody: true,

                    svgo: { removeStyleElement: true },

                },

                sprite: {

                    prefix:false

                }

            })

        ]

    });
`

Anyone have an idea why this occur ? Thanks !

**Comment by cascornelissen** [comment]
Nothing out of the ordinary as far as I can see 🤔 The last release was in May and I haven't seen any other issues about this so I don't think it's related to the plugin but let's try to find out. 

The only reason the generated sprite would be empty is if it can't find the input files so something might be wrong there. Can you tell a bit more about your environment(s)? Running stuff in containers? What's your current webpack version? Updated any other dependencies lately? If you're using git, any chance you can check your history for relevant changes?

**Comment by stereochuck** [comment]
I'm using using Webpack 4.43.0 with laravel mix.

didn't updated anything relevant that I can remember. My svgs for some reason cause problem. The strange part is, if I start from scratch and adding my faulty svgs one by one it will work but if I use these precise files it won't work (like there's a problem with some file).

I think it's cause by copy/pasting files during the watch of my files "npm run watch" of by creating an empty file with atom before pasting svg code inside. But I'm not sure.

Here's my faulty files. (Nothing fancy here, just logos and icons) I tried them on OSX after on my Ubuntu was problematic and I had the same result.
[sprite-test.zip](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/4805192/sprite-test.zip)

P.s. Problem occurs with svg created with Illustrator and svg copy/pasted from Figma.com.

Let me know if you have any clue.

**Comment by cascornelissen** [comment]
Hmm, that's really strange... I tried playing around with the files but couldn't really get it to break on my end. Would you be able to provide a repository with a minimal setup to reproduce the issue, preferably based on the [simple example](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/master/examples/simple)?
