### ISSUE TITLE
Expose SVG sprite asset filename to JS code

### ISSUE THREAD

**Issue by nikolay-borzov** [cascornelissen/svg-spritemap-webpack-plugin#114]
[webpack-svgstore-plugin](https://github.com/mrsum/webpack-svgstore-plugin) has a really useful feature - it sets values of magic variables (e.g. `__svg__`) in JS code with SVG sprite info (path, content, etc.). It allows implementing your own SVG sprite loading/integration. Use case: You don't have full control of HTML generating (e.g. cannot use HtmlWebpackPlugin because HTML is generated on BE side)

```
// This one will be updated on compilation
const SVG-SPRITEMAP-WEBPACK-PLUIGIN_DATA = {}

// Loads SVG sprite via AJAX and inserts inside page
fetchAndIntegrateSVGSprite(SVG-SPRITEMAP-WEBPACK-PLUIGIN_DATA.path)
```

**Comment by cascornelissen** [comment]
That sounds like an interesting feature, I'd be interested in a PR if anyone is willing to work this out ✌️

**Comment by nikolay-borzov** [comment]
I'm trying to use `DefinePlugin` to set the magic variable. But it looks like it's impossible. DefinePlugin only acts before `compilation` hook and we only know SVG sprite filename on `make` hooks. Maybe it's possible to calculate filename beforehand

**Comment by cascornelissen** [comment]
I'm a bit out of the loop on the Webpack internals to be fair but I don't think the hashes are available before the `compilation` hook so I don't think the `DefinePlugin` is ever going to work.
