### ISSUE TITLE
Sprite not rendering properly for sometimes in chrome

### ISSUE THREAD

**Issue by Arsadh** [cascornelissen/svg-spritemap-webpack-plugin#116]
@cascornelissen , Svg sprite are not rendered properly in chrome browser

**Comment by Netaxis-dev** [comment]
I am also facing the same issue in chrome.

CC:  @Arsadh

**Comment by cascornelissen** [comment]
Do you have some more information? Which version of the plugin are you using, can you share your SVGs or set up a minimal reproducible test case for me?

**Comment by Arsadh** [comment]
@cascornelissen , here i attached one svg which I used in sprite and my chrome version is `Google Chrome is up to date
Version 84.0.4147.89 (Official Build) (64-bit)` and laravel mix version I used is `"laravel-mix": "^5.0.1"`. <br>  Svg's are visible only after they are cached in browser

[random.zip](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/4974941/random.zip)

**Comment by cascornelissen** [comment]
Thanks for providing the SVG, there doesn't seem to be a problem with that. I need more info:

* Still no idea which version of the plugin you're using
* Still no idea which version of webpack is used, I suspect it comes with `laravel-mix`, if so what does `npm ls webpack` give?
* What configuration are you using for the plugin?

The following comment, combined with the simple SVG you've provided makes me pretty sure this is not an issue with the plugin.

> Svg's are visible only after they are cached in browser

This sounds like the spritemap gets cached by the browser, does the file have a hash in the filename (e.g. `spritemap.ba231h4.svg`) or is it just `spritemap.svg`? In case of the latter please use the [`output.filename`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#outputfilename--spritemapsvg) and set it to a value like `spritemap.[contenthash].svg`.

**Comment by Arsadh** [comment]
@cascornelissen , Thanks for your concern, this issue occurs because of the latest Chrome update.

`Reference issue` - https://bugs.chromium.org/p/chromium/issues/detail?id=1107442

**Comment by cascornelissen** [comment]
@Arsadh, thanks for diving deeper into this, that's a really interesting bug... The fix with the content hash won't solve the issue either in that case and I think the only way to fix this is with the Chrome team. Would you mind if we close this issue?

**Comment by Arsadh** [comment]
No, I don't mind @cascornelissen
