### ISSUE TITLE
dummy-module chunk is not deleted

### ISSUE THREAD

**Issue by nikolay-borzov** [cascornelissen/svg-spritemap-webpack-plugin#117]
`webpack`: `4.44.1`
`svg-spritemap-webpack-plugin`: `3.5.7`

Config like:
```js
module.exports = {
  mode: 'development',
  output: {
    path: '/shop-static/assets/',
    hashDigestLength: 8,
    filename: './js/[name].js',
    chunkFilename: './js/[name].js'
  },
  plugins: [
    new SVGSpritemapPlugin('./src/svg-icons/*.svg', {
      output: {
        filename: 'spritemap',
        svgo: {
          plugins: [{ removeTitle: true }]
        }
      }
    })
  ]
};
```

When I added `console.log` here:
```js
...
// Fetch existing filenames from all instances of this plugin
const filenames = compilation.options.plugins.filter((plugin) => plugin instanceof SVGSpritemapPlugin).map((plugin) => plugin.filename);
compilation.chunks.forEach((chunk) => {
  console.log(chunk.name, outputOptions.chunk.name)
...
```

I saw:

```
spritemap~._spritemap-dummy-module~1acb1ac1 spritemap
```

**Comment by cascornelissen** [comment]
@nikolay-borzov, the fix for this issue has been released in version [`3.5.8`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.5.8) 🚀 Thanks for reporting the bug and helping me debug it!

**Comment by nikolay-borzov** [comment]
Thank you for the quick fix!

**Comment by nikolay-borzov** [comment]
@cascornelissen, is it possible to exclude the dummy module from `stats.compilation.chunks`?

**Comment by cascornelissen** [comment]
I'm not sure but I don't think it is. The dummy module needs to be created and we can't get rid of it until the files are emitted and I'm pretty sure the stats are combined before that point...

But if you want to try it out, you can give it a go I guess.

**Comment by nikolay-borzov** [comment]
I see. Thanks.
