### ISSUE TITLE
Specify the output folder instead of webpack.output.path

### ISSUE THREAD

**Issue by alessandro308** [cascornelissen/svg-spritemap-webpack-plugin#137]
**Description**
I would like to specify an output folder different from the `webpack.output.path`.

**Comment by cascornelissen** [comment]
For some context, why exactly would you want to do that?

Webpack doesn't really give plugin maintainers the tools to support that so I'm a bit hesitant on adding this unless there's a solid reason for it. A better way might be to use something like [`event-hooks-webpack-plugin`](https://github.com/cascornelissen/event-hooks-webpack-plugin) and execute some logic when the `afterEmit` or `assetEmitted` hook is called.
