### ISSUE TITLE
referencing via fragment identifiers doesn't work

### ISSUE THREAD

**Issue by antonyd89** [cascornelissen/svg-spritemap-webpack-plugin#152]
As mentioned in the documentation:
Whether to include a <view> element for each sprite within the generated spritemap to allow referencing via fragment identifiers (https://css-tricks.com/svg-fragment-identifiers-work/). Passing a string will use the value as a postfix for the id attribute.

**Expected behavior**
If you write CSS background style and in the URL path mention particular fragment identifiers, then you will see the particular image from SVG sprite.

**Actual behavior**
the following style should load a particular image from SVG sprite, but it loads and shows the whole svg sprite. 

`backgroundimage: url("//localhost:8888/cdn/sprites/phone-spritemap.svg#svg-icon-lock-href") `

**System information**

Settings of the svg-spritemap-webpack-plugin:

>  new SVGSpritemapPlugin('resources/phone/assets/svg/**/*.svg', {
>             output: {
>                 filename: 'cdn/sprites/phone-spritemap.svg',
>             },
>             sprite: {
>                 prefix: 'svg-',
>                 generate: {
>                     title: false,
>                     symbol: "-href",
>                     use: true,
>                     view: "-href"
>                 }
>             },
>         }),
>

Could you help me find a solution on how to use approach "referencing via fragment identifiers"? Have I configured the settings correctly?

**Comment by antonyd89** [comment]
I found the mistake in my configs. Issue has been solved

**Comment by vdloc** [comment]
> I found the mistake in my configs. Issue has been solved

Can you show the correct configs for people who faced the same issue?
