### ISSUE TITLE
doesnt work with Imagemin webpack plugin

### ISSUE THREAD

**Issue by saltnpixels** [cascornelissen/svg-spritemap-webpack-plugin#160]
I am using a scripts build so I created a webpack.config file and extended the plugins and added this plugin in the hopes of having it generate the sprite.

```
const defaultConfig = require('scripts/config/webpack.config');
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');

defaultConfig.plugins.push(new SVGSpritemapPlugin('assets/svg/*.svg', { output: {filename: 'svg/symbol-defs.svg'}}))
module.exports = {
	...defaultConfig,
};
```

This creates the file, but its empty. Any ideas why?

**Comment by saltnpixels** [comment]
The scripts I am hooking into:
https://github.com/10up/10up-scripts/blob/develop/config/webpack.config.js

**Comment by saltnpixels** [comment]
Interestingly i think it works on watch but not build...

**Comment by saltnpixels** [comment]
After palying around I found that its the imagemin plugin... Its ruining the output... Anything I can do?

**Comment by cascornelissen** [comment]
I don't have much experience with the 10up scripts or the imagemin-webpack-plugin but IMO the most logical thing to do would be to exclude the generated spritemap from being minified by imagemin by using the [`test` option](https://www.npmjs.com/package/imagemin-webpack-plugin#optionstest) for that plugin.

This plugin already minifies the SVG using [`svgo`](https://www.npmjs.com/package/svgo) so there's no need to let imagemin minify the file again.
