### ISSUE TITLE
Add support for `base64` styles format

### ISSUE THREAD

**Issue by xavierfoucrier** [cascornelissen/svg-spritemap-webpack-plugin#165]
It would be cool to have **`base64` available as a styles format** here:
https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#stylesformat--data

> Just an suggestion :wink:

**Comment by cascornelissen** [comment]
Is there an advantage to that over the data URIs (e.g. using `styles.format: 'data'`) that are supported already? That approach uses [`mini-svg-data-uri`](https://www.npmjs.com/package/mini-svg-data-uri) which explains in its README that this results in a smaller filesize.

**Comment by xavierfoucrier** [comment]
Yep, exactly.

I was guessing that there will be an advantage to `base64` the SVG, in comparison to data URIs, but after a bunch of tests it looks like it's better to compile with `mini-svg-data-uri` instead.

Closing the issue! :rocket: :+1:
