### ISSUE TITLE
href instead of xlink:href

### ISSUE THREAD

**Issue by EdwardBock** [cascornelissen/svg-spritemap-webpack-plugin#176]
xlink:href is deprecated. It would be great if you could also support href which it seems you do not right now, are you?

https://www.w3.org/TR/SVG/linking.html#XLinkRefAttrs

**Comment by cascornelissen** [comment]
`xlink:href` is deprecated in the SVG 2.0 spec which I'm pretty sure is not final yet. I'm a bit hesitant on adding features based on a [specification that's still in draft](https://svgwg.org/svg2-draft/) and has - as far as I know - limited browser support.

If there's a specific problem you're running into I'm willing to consider it, though. Do you have some more information/context?

**Comment by EdwardBock** [comment]
Oh, I missed that SVG 2.0 is still in draft, sorry. I have no acute problems. Just stumbled on this deprecation warning on another issue (CSP and SVG -_-).
