### ISSUE TITLE
Windows pattern

### ISSUE THREAD

**Issue by TiDaGo** [cascornelissen/svg-spritemap-webpack-plugin#196]
pattern: like this new './src/files/sprite-images/**/*.svg'

in options-formatter.js
` output.input.patterns = output.input.patterns.map((pattern) => {
        console.log(pattern);
        var result = path.normalize(pattern);
        console.log(result);
        return result;
    });`

pattern like my, but result like windows ) 
.\src\files\sprite-images\**\*.svg

and in index.js
` glob.sync(pattern, inputOptions.options).map((match) => {`
not working with this pattern.

**Comment by TiDaGo** [comment]
Thx, Now it's working !
but my package.json - 
"svg-spritemap-webpack-plugin": "github:cascornelissen/svg-spritemap-webpack-plugin#master",

))))

**Comment by TiDaGo** [comment]
Thx, Now it's working !
but my package.json -
"svg-spritemap-webpack-plugin": "github:cascornelissen/svg-spritemap-webpack-plugin#master",

))))

**Comment by cascornelissen** [comment]
I have just published [`4.4.2`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v4.4.2) to npm. Thanks for testing! ❤️
