### ISSUE TITLE
Empty output file when the style attribute contains either "visibility: hidden" or "display: none"

### ISSUE THREAD

**Issue by rku4er** [cascornelissen/svg-spritemap-webpack-plugin#209]
When I set either "visibility: hidden" or "display: none" as a style attribute, the plugin produces an empty SVG sprite. While I'm not entirely sure if this is a bug or not, I consider it to be incorrect behavior. It's often necessary to hide the SVG sprite visually when inserting it on a page. Am I missing anything in the settings?

My config is pretty simple:
```
	plugins: [
		...defaultConfig.plugins,
		new SVGSpritemapPlugin(
			'src/icons/*.svg',
			{
				output: {
					filename: 'symbols/svg-icons.php',
					svg: {
						attributes: {
							style: 'position: absolute; visibility: hidden;'
						}
					}
				},
				sprite: {
					prefix: 'svg-icon-',
					generate: {
						title: false
					}
				}
			}
		)
	]
```

**Comment by rku4er** [comment]
It has been fixed by setting svgo: false :)

**Comment by cascornelissen** [comment]
Great that you figured out it's SVGO doing this, if I had to guess it's the [removeHiddenElemens plugin](https://github.com/svg/svgo/blob/main/plugins/removeHiddenElems.js). If you do want to use the other features that SVGO has, you can also specifically disable that plugin by passing an object to the [`svgo` option](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/HEAD/docs/options.md#outputsvgo--true) as well.

**Comment by rku4er** [comment]
Thanks for the hint! If anyone else needs this, I used these settings:
```
	svgo: {
		plugins: [
			{
				name: 'removeHiddenElems',
				active: false
			}
		]
	}
```
