### ISSUE TITLE
Add `mask` support

### ISSUE THREAD

**Issue by xavierfoucrier** [cascornelissen/svg-spritemap-webpack-plugin#212]
Hello @cascornelissen 👋 

Great plugin, I am using it in many `scss` projects.

One thing I noticed is that it would be convenient, in some situations, to output the `mask` attribute instead of `background`.
This could be implemented by using a using a different mixin like `mask(..)` or adding parameters to the current `sprite` one.

Thanks a lot!

> I know that you can tweak the `svg` by passing custom variables, but `mask` is usefull especially when you have to use `mask-size: 100% 100%;`, because `width`/`height`/`viewbox` are removed from the `data:image` output.

PS: my mistake, you can tag this as "feature request" 👌

**Comment by cascornelissen** [comment]
Hi! Thanks for the feature request, I'm open to reviewing and merging a PR to land this feature.

We do a similar thing already when it comes to `background-size` or `width` + `height` in the SCSS mixin (see below) so having an extra argument (e.g. `$property` that defaults to `background` but can be set to `mask`) would work I guess?

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/c0f2d3d7b5657505b03ff81abe1e50bfa0716e36/lib/templates/styles.scss#L59-L67

**Comment by xavierfoucrier** [comment]
This should be great!

> Work overflow on my side right now, but I can find time during my vacations to work on this 🏂

**Comment by xavierfoucrier** [comment]
Hello @cascornelissen 👋 

Currently working on this 😉 
By default it would be nice to set `$include-size: true` for the `sprite` helper, this could be useful and make sense: what do you think?

> I also found another bug in the package, related to `prefix`: I will open a different issue for that.

**Comment by xavierfoucrier** [comment]
Bump @cascornelissen 😎

**Comment by cascornelissen** [comment]
Apologies for taking a while, I've been enjoying some holidays 🏝️ It's on my list to take a look.

**Comment by cascornelissen** [comment]
Merged the PR and made some adjustments in 1ae47996b4ef6b6197a4a867e454ca396559f373, would you mind verifying that things still work as expected with the latest commits before I publish a new release? 😊 

```shell
npm install cascornelissen/svg-spritemap-webpack-plugin#master
```

**Comment by xavierfoucrier** [comment]
Hello @cascornelissen 👋 

All is working fine.
May be update the documentation accordingly? I am not sure I did this already 😄 

Another point, what do you think of setting `$include-size: true` for the `sprite` helper by default?
This is clearly something that could be useful for developers and it's making sense.

Thanks for the code update, all looks fine to me 😎

**Comment by xavierfoucrier** [comment]
@cascornelissen great to hear!

Agree with you 😉 
Thanks again for publishing it 🚀
