### ISSUE TITLE
Minor/Patch release request

### ISSUE THREAD

**Issue by pciarach** [cascornelissen/svg-spritemap-webpack-plugin#215]
**Description**
Hello, it would be nice to create a new minor/patch version bump including dependencies upgrades that Dependabot bumped since the last release 😊

**Additional context**
https://github.com/cascornelissen/svg-spritemap-webpack-plugin/compare/v4.5.0...master

**Comment by cascornelissen** [comment]
Sorry for taking a while, I've just pushed [v4.5.1](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v4.5.1) 🚀
