### ISSUE TITLE
[Question] Rspack compatibility

### ISSUE THREAD

**Issue by sectsect** [cascornelissen/svg-spritemap-webpack-plugin#217]
A webpack-compatible replacement [Rspack](https://rspack.dev/) v1 has been released.
It seems that there are some errors when running this package on Rspack.

I understand that this plugin is basically for webpack.
Do you have a plan to support Rspack?

**Comment by cascornelissen** [comment]
No plans from my side but if the required changes are manageable I’m willing to review some PRs.
