### ISSUE TITLE
Webpack doesn't rebuild on file change

### ISSUE THREAD

**Issue by DreadBoy** [cascornelissen/svg-spritemap-webpack-plugin#27]
If I use Webpack in watch mode and change one of source .svg, Webpack doesn't rebuild app. Is this intended? If it is, is there a way to trick Webpack to watch for changes in source files?

**Comment by cascornelissen** [comment]
Which version of the plugin are you using?

**Comment by DreadBoy** [comment]
svg-spritemap-webpack-plugin@2.3.0 and webpack@4.6.0

Config is like this:

```
const spritePlugin = new SVGSpritemapPlugin({
    src: 'src/svg/*.svg',
});

module.exports = {
....
    plugins: [
        extractSASS,
        spritePlugin,
    ],
...
}
```

**Comment by cascornelissen** [comment]
Hmm, watching was added in `2.1.0`.

Which OS are you using and would it be possible to share a small test case which fails on your end?

**Comment by DreadBoy** [comment]
Windows 10 Pro, will include test case shortly

**Comment by DreadBoy** [comment]
https://github.com/DreadBoy/svg-spritemap-webpack-plugin-27

**Comment by cascornelissen** [comment]
Thanks for the test-case, I'm looking into it right now.

**Comment by cascornelissen** [comment]
@DreadBoy, this seems to be an issue that's been introduced in `2.2.0`. You could use `2.1.0` until I've fixed the issue and released a new version by running:

```
npm install svg-spritemap-webpack-plugin@2.1.0
```

**Comment by cascornelissen** [comment]
@DreadBoy, I've fixed the issue (including some related issues introduced since webpack `4.6.0`) and it's available in the `master` branch. Could you report if it fixes the issues on your end too?

```shell
npm install --save-dev cascornelissen/svg-spritemap-webpack-plugin#master
```

I'll release `2.4.0` when I hear back from you!

**Comment by DreadBoy** [comment]
Yeah, I confirm it works, thanks for fixing it!

**Comment by cascornelissen** [comment]
Release [`2.4.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v2.4.0) has been published to GitHub and npm.

@DreadBoy, thanks for the test-case which helped me solve this issue a lot quicker! :v:
