### ISSUE TITLE
Change settings doesn`t affect to result svg

### ISSUE THREAD

**Issue by schrodinger-cat** [cascornelissen/svg-spritemap-webpack-plugin#29]
Hi, I trying to migrate from gulp to webpack and I need to generate svg sprite. But when sprite is generated, settings doesn't not affect the outcome. I have svg named `logo.svg`, and I expect `symbol` with id `icon-logo`, but I get:

```
<symbol id="a" viewBox="0 0 512 512">...
```

Run at MacOS High Sierra 10.13.4, webpack version 4.8.0, config:
```
new SVGSpritemapPlugin({
  src: 'assets/svg/**/*.svg',
  filename: '../svg/sprite.svg',
  prefix: 'icon-',
  svgo: {
    plugins: [
      {
        removeTitle: false,
        minify: false,
        removeXMLNS: true,
      },
    ],
  },
}),
```

**Comment by cascornelissen** [comment]
1. Could you provide the source SVG?
1. The `filename` can't be a path, don't think that's the problem here, though.
1. Does it work without the `svgo` configuration?

**Comment by schrodinger-cat** [comment]
1. ``` <?xml version="1.0" encoding="UTF-8"?>
<svg enable-background="new 0 0 512 512" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
		<path d="m170.67 341.33c-51.755 0-93.867 42.112-93.867 93.867v76.8h17.067v-76.8c0-42.351 34.458-76.8 76.8-76.8h25.6v-17.067h-25.6z"/>
		<path d="m290.13 298.67v50.031l-34.133 122.88-34.133-122.88v-50.031h-17.067v51.2c0 0.776 0.102 1.544 0.316 2.287l42.667 153.6c1.023 3.686 4.386 6.246 8.217 6.246s7.202-2.56 8.226-6.246l42.667-153.6c0.196-0.742 0.307-1.51 0.307-2.287v-51.2h-17.067z"/>
		<circle cx="204.8" cy="179.2" r="17.067"/>
		<circle cx="307.2" cy="179.2" r="17.067"/>
		<path d="m284.1 232.89c-9.404 9.395-21.888 14.566-35.183 14.575h-9.984v17.067h9.984c17.852-8e-3 34.628-6.955 47.249-19.567l-12.066-12.075z"/>
		<path d="m252.74 213.33l10.888-21.777-15.266-7.637-17.067 34.133c-1.323 2.645-1.178 5.786 0.375 8.303 1.562 2.509 4.301 4.045 7.262 4.045h25.6v-17.067h-11.792z"/>
		<path d="m341.33 145.07v68.267c0 47.053-38.281 85.333-85.333 85.333s-85.333-38.281-85.333-85.333h-17.067c0 56.465 45.935 102.4 102.4 102.4s102.4-45.935 102.4-102.4v-68.267h-17.067z"/>
		<path d="m375.48 213.33v43.767c-8e-3 7.62-3.362 14.78-9.224 19.652l-38.912 32.427 10.931 13.116 38.904-32.427c9.762-8.124 15.36-20.07 15.369-32.759v-43.776h-17.068z"/>
		<path d="M256,0c-79.991,0-145.067,65.075-145.067,145.067v17.067H128v-17.067c0-70.579,57.421-128,128-128s128,57.421,128,128    v17.067h17.067v-17.067C401.067,65.075,335.992,0,256,0z"/>
		<path d="m366.93 145.07h-17.067c-4.719 0-8.533 3.823-8.533 8.533v68.267c0 4.71 3.814 8.533 8.533 8.533h17.067c23.526 0 42.667-19.14 42.667-42.667 0-23.526-19.14-42.666-42.667-42.666zm0 68.266h-8.533v-51.2h8.533c14.114 0 25.6 11.486 25.6 25.6s-11.486 25.6-25.6 25.6z"/>
		<path d="m145.07 213.33c-14.114 0-25.6-11.486-25.6-25.6s11.486-25.6 25.6-25.6v-17.067c-23.526 0-42.667 19.14-42.667 42.667 0 23.526 19.14 42.667 42.667 42.667h17.067v-17.067h-17.067z"/>
		<rect x="153.6" y="170.67" width="17.067" height="51.2"/>
		<path d="m256 34.133c-61.167 0-110.93 49.766-110.93 110.93v34.134c0 2.961 1.536 5.7 4.045 7.262 1.374 0.845 2.927 1.271 4.489 1.271 1.306 0 2.611-0.299 3.806-0.896l146.24-73.114c11.998 20.275 29.815 36.966 50.935 47.514 2.662 1.323 5.794 1.178 8.303-0.375 2.517-1.562 4.053-4.301 4.053-7.262v-8.533c-1e-3 -61.167-49.767-110.93-110.93-110.93zm58.837 64.461c-1.007-2.022-2.782-3.567-4.932-4.284-2.142-0.725-4.489-0.546-6.519 0.461l-141.25 70.622v-20.326c0-51.755 42.112-93.867 93.867-93.867 49.57 0 90.283 38.613 93.645 87.347-14.713-10.12-26.813-23.944-34.809-39.953z"/>
		<path d="m203.65 396.77c-1.792-3.055-5.299-4.676-8.772-4.113l-29.201 4.864 54.332-67.917-13.329-10.667-68.267 85.333c-2.21 2.765-2.492 6.605-0.7 9.651 1.783 3.046 5.274 4.634 8.764 4.096l45.389-7.569 56.764 97.314 14.754-8.593-59.734-102.4z"/>
		<path d="m341.33 341.33h-25.6v17.067h25.6c42.351 0 76.8 34.449 76.8 76.8v76.8h17.067v-76.8c0-51.755-42.112-93.867-93.867-93.867z"/>
		<path d="m373.61 404.27l-68.267-85.333-13.337 10.666 54.34 67.917-29.21-4.864c-3.447-0.538-6.98 1.058-8.772 4.113l-59.733 102.4 14.746 8.602 56.772-97.314 45.397 7.561c3.43 0.546 6.963-1.041 8.755-4.096 1.793-3.056 1.52-6.887-0.691-9.652z"/>
		<path d="m375.47 477.87h-68.267c-4.719 0-8.533 3.814-8.533 8.533v25.6h17.067v-17.067h51.2v17.067h17.066v-25.6c0-4.719-3.814-8.533-8.533-8.533z"/>
		<rect x="332.8" y="460.8" width="17.067" height="25.6"/>
</svg>
 ```
2. I try it without path – same result
3. No, it still same

**Comment by schrodinger-cat** [comment]
Hmm, I trying to create a minimal test case, and it works fine. The problem was that the imagemin-webpack-plugin plugin was used, and by default it minimize `svg`.

**Comment by cascornelissen** [comment]
Ah, that explains why the `id` was changed to `a`, yeah. 

You're probably better off disabling the `imagemin-webpack-plugin` for SVGs or disabling the `cleanupIDs` task through [`options.svgo`](https://github.com/Klathmon/imagemin-webpack-plugin#optionssvgo) when using SVGs outside of the spritemap.
