### ISSUE TITLE
Missing option to disable title

### ISSUE THREAD

**Issue by Hoet** [cascornelissen/svg-spritemap-webpack-plugin#30]
Hello,

I was wondering how I could disable the title of an generated icon ?
I can't find an option to disable the auto generating of a title.

My icons are constructed like below. The title "toevoegen" is only active when you over over a part of the icon that has no content. Else the title "add_circle" is displayed.
```
<a href="/customer-service/patients/new/" title="Toevoegen">
  <svg class="icon " }}="">
      <use xlink:href="/dist/sprites.svg#add_circle"></use>
  </svg>
</a>
```

I have changed this in my npm folder. This seems to be working well. Mind you this is my first time I changed a npm package. 
```
function SVGSpritemapPlugin(options) {
    // Merge specified options with default options
    this.options = merge({
        src: '**/*.svg',
        svgo: {},
        glob: {},
        prefix: 'sprite-',
        gutter: 2,
        filename: 'spritemap.svg',
        chunk: 'spritemap',
        deleteChunk: true,
        svg4everybody: false,
        generateTitle: true                   <--- Added 
    }, options, {
        svgo: {
            plugins: [{
                cleanupIDs: false
            }]
        }
    });
}
```
```
// Generate a title or not ?
if( options.generateTitle == true ) {    <--- Added 
  // Make sure we don't overwrite the existing title
  var hasTitle = false;
  for ( var i = 0; i < svg.childNodes.length; i++ ) {
    if ( svg.childNodes[i].tagName && svg.childNodes[i].tagName.toLowerCase() === 'title' ) {
      var hasTitle = true;
    }
  }

  // Add title for improved accessibility
  if ( !hasTitle ) {
      var title = XMLDoc.createElement('title');
      title.appendChild(XMLDoc.createTextNode(id.replace(options.prefix, '')));
      symbol.appendChild(title);
  }
}   

```

**Comment by cascornelissen** [comment]
A solution would be to add an empty title tag to the SVG itself. Would that work you for?

```
<title></title>
```

**Comment by Hoet** [comment]
Would be an option, but in that case I'll have to check and edit around 240 svg files. Well not me, but another developer ;). And when adding a new svg be it from the materials design library, iconfinder or another library the developer will have to check if there is an title in the file and change it accordingly. This is something that will be forgotten on a regular basis. Which means that we have to look at the code a couple times to get it just right.

In this project I'am working on the title is set on the icon wrapper automatically. It is a translated string comming from a DB field that is translated. If you ask me think that you should have this as an option. So the developer can decide if he wants default titles (generated), the titles that might be present (or placed there by the developer) in the used svg file or use his/her own because the icon is wrapped inside a container that carries the title.

With the option above you will have all three options at your disposal. Actually 4 options as you are also able to forgo with a title all together.

In the end it is your package, so I'll leave the disission up to you :)

**Comment by cascornelissen** [comment]
Thing is I noticed you're using the `1.x` release which I'm not actively working on anymore. 

You're free to submit two PRs (both on the `1.x` and `master` branches) with this new feature. I'm willing to look at the PR and release a new version if you want 😉

**Comment by Hoet** [comment]
Correct, I'm forced to use 1.x for now. To many things need to change in this project to be able to use 2.x. And seeing I have only 2 weeks left in this project I'm not going to touch that ;)

Alright, I'll do that.

**Comment by Hoet** [comment]
Do I need to be added to the project before I can push a branch ?

5:34 PM	Push failed: Failed with error: unable to access 'https://github.com/cascornelissen/svg-spritemap-webpack-plugin.git/': The requested URL returned error: 403

**Comment by cascornelissen** [comment]
You'll have to fork it and submit a PR. [This guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) on how to contribute might help you 😉

**Comment by Hoet** [comment]
Pull requests have been submitted. I have been unable to test the changes to 2.x as I have no environment to test that at this time.

**Comment by cascornelissen** [comment]
Thanks, I'll try to look into it this weekend!

**Comment by cascornelissen** [comment]
@Hoet, I had a quick glance at the PRs, they look fine and I'll try merge them when I have the time to release new versions.

**Comment by cascornelissen** [comment]
Version [`1.2.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v1.2.0) and [`2.5.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v2.5.0) containing this feature have just been released and published to npm.

Thanks for your contribution, @Hoet! 🚀
