### ISSUE TITLE
`filename` doesn't work well with Webpacker

### ISSUE THREAD

**Issue by osvaldasvalutis** [cascornelissen/svg-spritemap-webpack-plugin#34]
I've tried changing the value of the `filename`, e.g.:

```
filename: 'something.svg',
```

However, it Webpacker's `manifest.json` it appears as:

```
"spritemap.svg": "/packs/something.svg",
```

As a matter of fact, this `asset_pack_path('something.svg')` doesn't work and most importantly it's not possible to have multiple sprite files. Not sure if it's a problem of the plugin though.

**Comment by cascornelissen** [comment]
Mind sharing the versions of webpack and the plugin, your webpack configuration, and the console output you get when running webpack? 😄

**Comment by osvaldasvalutis** [comment]
It happens on both `@rails/webpacker@4.0.0-pre.2` + `svg-spritemap-webpack-plugin@2.4.0` and `@rails/webpacker@3.2.2` + `svg-spritemap-webpack-plugin@1.1.1` combinations. Here's the related console output:

```
something.svg   12.6 KiB    spritemap  [emitted]  spritemap
spritemap-79a85969a7ee0ba5.chunk.js.map  101 bytes    spritemap  [emitted]  spritemap
```

**Comment by cascornelissen** [comment]
I don't know about Webpacker but maybe it uses the name of the chunk in it's stats? Does adding the following to the `SVGSpritemapWebpackPlugin` options solve it?

```
chunk: 'something'
```

See: https://github.com/cascornelissen/svg-spritemap-webpack-plugin#chunk--spritemap

**Comment by osvaldasvalutis** [comment]
This helped! I somehow passed over the `chunk` option, sorry.

**Comment by cascornelissen** [comment]
Awesome, no problem at all! ✌️
