### ISSUE TITLE
generated scss map not available under the specified filename in styles parameter

### ISSUE THREAD

**Issue by janwidmer** [cascornelissen/svg-spritemap-webpack-plugin#35]
When using the plugin with a custom `styles` parameter, e.g. `styles: '~icons.scss'`, I would expect to be able to call the map mixin like this:

```
@import '~svg-spritemap-webpack-plugin/icons';
background-image: url(map-get($icons, 'logo'));
```

Currently, that gives me an error, ` Undefined variable: "$icons"`. Therefore it seems, that the generated map always get's stored in the variable `$sprites`

So this is working

```
@import '~svg-spritemap-webpack-plugin/icons';
background-image: url(map-get($sprites, 'logo'));
```

Is that intended or should the map variable be available under the same same as specified in the `styles` parameter?

**Comment by cascornelissen** [comment]
That's intended for now, the variable name is always `$sprites` at the moment. We can't really change it to the `styles` parameter as that could contain invalid characters and it would not be BC.

The current setup might also cause problems when using multiple instances of the plugin to generate multiple spritemaps so I guess this is something we'll have to look into.

Maybe we could support an object (as well as the current string setup) for the `styles` option.

```
styles: {
    filename: '~icons.scss',
    variables: {
        sprites: 'sprites' // 'icons' in your case,
        variables: 'variables' // currently introduced in the `vars` branch
    }
}
```

**Comment by janwidmer** [comment]
ah ok, good to know, then I will close that ticket. Having an object for multiple instances would be a solution..

Great plugin by the way, thank you!

**Comment by cascornelissen** [comment]
Mind if I keep this open? I want to look into this as I'm guessing multiple people will be running into this in the future. I'll see if I can release a fix in the next few weeks and will use this issue to track progress.

**Comment by janwidmer** [comment]
sure :-)

**Comment by cascornelissen** [comment]
@janwidmer, this has been added in the `3.x` release which is currently a Release Candidate, you can install this version using:

```shell
npm install svg-spritemap-webpack-plugin@next
```

The original issue you reported should be fixable by using the following options, the rest of your configuration might need some restructuring for this version as well so be sure to check the new [documentation on options](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/v3.0.0-rc.2/docs/options.md).

```
new SVGSpritemapPlugin({
    styles: {
        filename: '~icons.scss',
        variables: {
            sprites: 'icons'
        }
    }
});
```

Is this something you could check? If so, I'd love to hear the results so I can finish up the upcoming major release.

**Comment by cascornelissen** [comment]
ping @janwidmer

**Comment by janwidmer** [comment]
ok that also works..the remaining question now is, if the mixin name should also be adjusted..or if there should be a config parameter for that also..? :-) Because the mixin name currently still stays sprite()

**Comment by cascornelissen** [comment]
[Way ahead of you!](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#stylesvariablesmixin--sprite)

**Comment by janwidmer** [comment]
haha nice one, didn't see that.. :-D also works perfectly

**Comment by cascornelissen** [comment]
Awesome, great to hear!
