### ISSUE TITLE
Having multiple sprites in scss possible?

### ISSUE THREAD

**Issue by Sebsemillia** [cascornelissen/svg-spritemap-webpack-plugin#47]
Hi,

I'm trying to get multiple sprites working with scss. The files get generated, but when I import them in my scss file, the last imported one overrules the other ones of course.

```
plugins: [
            new SVGSpritemapPlugin({
                src: 'gfx/svg/common/*.svg',
                filename: 'gfx/common-sprite.svg',
                prefix: 'common-sprite-',
                gutter: 2,
                styles: 'src/css/_common_sprite.scss'
            }),
            new SVGSpritemapPlugin({
                src: 'gfx/svg/pdp/*.svg',
                filename: 'gfx/pdp-sprite.svg',
                prefix: 'pdp-sprite-',
                gutter: 2,
                styles: 'src/css/_pdp_sprite.scss'
            })
]
```

```
@import "common_sprite";
@import "pdp_sprite";
```

So my question is, is it possible to target specific sprites in scss?

Maybe like this?
```
@include sprite('icon-name', 'sprite-name);
```

Thank you very much for this nice plugin! :)

**Comment by cascornelissen** [comment]
This is not possible at the moment and something I'm hoping to resolve in the next major release [(`3.0.0`)](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/milestone/1) of this plug-in as it requires a rewrite of the options object which will be backwards incompatible.

See https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/35#issuecomment-393495046 for more information.

**Comment by Sebsemillia** [comment]
Thank you very much for your quick reply. Looking forward to your next major release :)

**Comment by cascornelissen** [comment]
Mind if I leave it open? That'll make the milestone easier to track 😄

**Comment by cascornelissen** [comment]
@Sebsemillia, this has been added in the `3.x` release which is currently a Release Candidate, you can install this version using:

```shell
npm install svg-spritemap-webpack-plugin@next
```

The original issue you reported should be fixable by using the following options, the rest of your configuration might need some restructuring for this version as well so be sure to check the new [documentation on options](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/v3.0.0-rc.2/docs/options.md).

```
new SVGSpritemapPlugin('gfx/svg/common/*.svg', {
    sprite: {
        prefix: 'common-sprite-',
    },
    styles: {
        filename: 'src/css/_common-sprites.scss',
        variables: {
            sprites: 'common-sprites',
            sizes: 'common-sizes',
            variables: 'common-variables',
            mixin: 'common-sprite'
        }
    }
});
new SVGSpritemapPlugin('gfx/svg/pdp/*.svg', {
    sprite: {
        prefix: 'pdp-sprite-',
    },
    styles: {
        filename: 'src/css/_pdp-sprites.scss',
        variables: {
            sprites: 'pdp-sprites',
            sizes: 'pdp-sizes',
            variables: 'pdp-variables',
            mixin: 'pdp-sprite'
        }
    }
});
```

Is this something you could check? If so, I'd love to hear the results so I can finish up the upcoming major release.

**Comment by cascornelissen** [comment]
ping @Sebsemillia

**Comment by cascornelissen** [comment]
Just verified this should still work as described in https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/47#issuecomment-425973238, I'm closing the issue as I want to finish the milestone and release `3.0.0`.
