### ISSUE TITLE
[Question]Inject sprite to html after compile?

### ISSUE THREAD

**Issue by borm** [cascornelissen/svg-spritemap-webpack-plugin#48]
Subj

**Comment by cascornelissen** [comment]
In what way? Are you using something like [`html-webpack-plugin`](https://www.npmjs.com/package/html-webpack-plugin)?

**Comment by borm** [comment]
yes

**Comment by cascornelissen** [comment]
The generated spritemap ends up in the webpack assets with a [chunk name](https://github.com/cascornelissen/svg-spritemap-webpack-plugin#chunk--spritemap), this should allow you to target it when using a [custom template](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md), see [this example](https://github.com/jantimon/html-webpack-plugin/blob/master/examples/custom-template/template.html#L9) for more info.

**Comment by borm** [comment]
Don`t understand, 
where chunk output
how i should require it

```
<%= require('html-loader!../spritemap') %>
```

**Comment by cascornelissen** [comment]
@borm, read the docs for `html-webpack-plugin`, it's in there, I don't really use it myself so I can't really help you. It's possible to target files or custom options in an `.ejs` file like this:

```
<% htmlWebpackPlugin.files %>
```

It should also be possible to get the source content of a file/asset via the `compile.assets[]` array and the `source()` function:

```
<%= compilation.assets[??].source() %>
```

**Comment by borm** [comment]
```js
new SVGSpritemapPlugin({
      src: ['src/icons/*.svg', 'src/icons/flags/*.svg'],
      filename: 'dist/sprite.svg',
      prefix: 'icon-',
      chunk: 'spritemap',
      deleteChunk: false,
      styles: path.join(__dirname, 'src/_sprites.scss'),
    }),
```

```html
<pre>
  <%= JSON.stringify(htmlWebpackPlugin.files, 0, 2) %>
</pre>
```

output
```json
{
--
  | "publicPath": "",
  | "chunks": {
  | "vendors~app": {
  | "size": 1763912,
  | "entry": "dist/vendors~app.js",
  | "hash": "e5ac2dc6a01f80ebfe1b",
  | "css": [
  | "dist/vendors~app.css"
  | ]
  | },
  | "app": {
  | "size": 653824,
  | "entry": "dist/app.js",
  | "hash": "31d69e6c1451af924090",
  | "css": [
  | "dist/app.css"
  | ]
  | }
  | },
  | "js": [
  | "dist/vendors~app.js",
  | "dist/app.js"
  | ],
  | "css": [
  | "dist/vendors~app.css",
  | "dist/app.css"
  | ]
  | }


```

**Comment by cascornelissen** [comment]
@borm, can you also post the entire webpack output and the output of the following code in the ejs template?

```
<pre>
  <%= JSON.stringify(compilation.assets, 0, 2) %>
</pre>
```

**Comment by borm** [comment]
veeeeeery big output

**Comment by cascornelissen** [comment]
Haha, I would've guessed. You can add it as an attachment if you want to?

**Comment by borm** [comment]
[r.txt](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/2354051/r.txt)

**Comment by borm** [comment]
ah, i see "spritemap.svg"

**Comment by borm** [comment]
as i understood i can use it
```<%= compilation.assets["spritemap.svg"]._value %>```

**Comment by cascornelissen** [comment]
No idea why it doesn't show up when printing the array but if it works it works, right?

**Comment by borm** [comment]
yes

**Comment by borm** [comment]
Up, how get it in version `3.3.5`

```
new SVGSpritemapPlugin('src/icons/!*.svg', {
      output: {
        filename: 'dist/sprite.svg',
        chunk: {
          name: 'spritemap',
          keep: true,
        },
      },
      sprite: {
        prefix: 'icon-',
        gutter: 8,
        generate: {
          title: false,
        },
      },
      styles: false,
    }),
```

`<%= JSON.stringify(compilation.assets["dist/sprite.svg"], 0, 2) %>` 
`<%= JSON.stringify(compilation.assets["spritemap.svg"], 0, 2) %>` 
`<%= JSON.stringify(compilation.assets["spritemap"], 0, 2) %>`
Nothing printed

**Comment by cascornelissen** [comment]
@borm, can you confirm that it works with `3.4.4`? It might be related to changes made in #79.

**Comment by borm** [comment]
@cascornelissen maybe you mean ```3.4.0```?

don`t worked

**Comment by cascornelissen** [comment]
@borm, no I meant `3.3.4`, sorry for the typo. The changes introduced by #79 were released in `3.3.5` so I was wondering if it was related to that. But also some more fixes were added and released in `3.3.6`, `3.3.7` and `3.4.0`. Can you also check the latest version if `3.3.4` works?

**Comment by borm** [comment]
don`t work

**package.json**
```"svg-spritemap-webpack-plugin": "^3.3.4",```

**webpack.config.babel.js**
```
new HtmlWebpackPlugin({
      template: 'index.html',
      filename: 'index.html',
    }),
new SVGSpritemapPlugin(['src/icons/!*.svg'], {
      output: {
        filename: 'dist/icons.svg',
        chunk: {
          name: 'dist/icons.svg',
          keep: true,
        },
      },
      sprite: {
        prefix: 'icon-',
        gutter: 8,
        generate: {
          title: false,
        },
      },
      styles: false,
    }),
```

**index.html**
```
<%= JSON.stringify(compilation.assets["dist/sprite.svg"], 0, 2) %>
```

**Comment by borm** [comment]
```3.3.4``` works

**Comment by cascornelissen** [comment]
Looks like we were thinking the same thing, I've just added a minimal [`inline-html`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/master/examples/inline-html) example to the repository. Great to hear it's working with `3.4.0` for you as well!
