### ISSUE TITLE
Collision with Bootstrap 4 on $sizes namespace

### ISSUE THREAD

**Issue by illepic** [cascornelissen/svg-spritemap-webpack-plugin#49]
The `$sizes` variable in the generated output scss is colliding with the same variable name used by Bootstrap 4.

Is there a way to change variable names or at least scope the variables to a namespaces in a minor release?

**Comment by cascornelissen** [comment]
@illepic, this has been added in the `3.x` release which is currently a Release Candidate, you can install this version using:

```shell
npm install svg-spritemap-webpack-plugin@next
```

The original issue you reported should be fixable by using the following options, the rest of your configuration might need some restructuring for this version as well so be sure to check the new [documentation on options](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/v3.0.0-rc.2/docs/options.md).

```
new SVGSpritemapPlugin({
    styles: {
        variables: {
            sizes: 'new-variable-name',
        }
    }
});
```

Is this something you could check? If so, I'd love to hear the results so I can finish up the upcoming major release.

**Comment by illepic** [comment]
Dropped right in with no problems: https://github.com/phase2/particle/pull/400/files

**Comment by cascornelissen** [comment]
Awesome, thanks for the update! 🎉
