### ISSUE TITLE
Documentation is incompatible with current version: 2.7.1

### ISSUE THREAD

**Issue by mfc3370** [cascornelissen/svg-spritemap-webpack-plugin#54]
The documentation referenced on READ.md `https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md` is for the next (versions 3.xxx). Can you please make this clear in the documentation? It's otherwise very confusing.

Thanks.

**Comment by cascornelissen** [comment]
Good point. Will add a note about this ASAP. Sorry for any confusion this may have caused!

**Comment by cascornelissen** [comment]
@mfc3370,  added in d4e541c, that should clear things up. Thanks again for the feedback 😄
