### ISSUE TITLE
Add support for SVG fragments in CSS

### ISSUE THREAD

**Issue by stasgavrylov** [cascornelissen/svg-spritemap-webpack-plugin#56]
Hi, first of all thanks for the great plugin, working with SVG icons is much easier with it.

Today, I've decided to try to use generated sprite in CSS background property.
This technique is supported in most modern browsers, and you can see an example here – 
http://jsfiddle.net/simurai/7GCGr/

Unfortunately, it seems that the current generated sprite output (specifically, `<symbol>` element) does not support this functionality. 
When I add a style declaration like `background: url('/icons-sprite.svg#plus') no-repeat;` the whole sprite is included, not a single fragment. And when I try to limit it's size, the sprite is scaled as a whole as well.

I was wondering if it's possible to extend current configuration options to support the kind of output needed to allow using svg fragments from external sprites in CSS.
This is an example of svg sprite which allows to included separate fragments – http://xn--dahlstrm-t4a.net/tmp/sharp-icons/svg-icon-target.svg

I'm sorry for not providing more constructive feedback, and I hope I'll have time to investigate the issue further in future. But since you obviously know more about SVGs that I do, I just wanted to plant this thought and maybe discuss it a bit more.

It is entirely possible that I am missing something and this should be working out of the box.
I am using `3.0.0` version with webpack 4.

Thanks.

Edit:
I've decided to add my current config just in case
```
    new SVGSpritemapPlugin('./src/assets/icons/**/*.svg', {
      output: {
        filename: 'icons-sprite.svg',
        svg4everybody: false,
      },
      sprite: {
        prefix: false,
      },
```

Edit2:
Upon further investigation, I've figured out that the only thing missing from output in order to be able to use svg fragments in CSS is style tag which could look similar to the following:
```
<style>
    symbol { display: none }
    symbol:target { display: inline }
</style>
```
Looking at the docs, there's no way to include such tag in output file, right?

Also, dimensions of fragments included in CSS seem to be affected by `width` and `height` attributes on `<use>` element in the sprite.
Here's the same icon used as background with the following properties
```
  background-image: url('/icons-sprite.svg#alert');
  background-size: 100px;
```
with `<use xlink:href="#alert" width="28" height="24"/>`:
![image](https://user-images.githubusercontent.com/9000614/48868413-242b2800-ede2-11e8-8085-21825a099477.png)
and with `<use xlink:href="#alert" />`:
![image](https://user-images.githubusercontent.com/9000614/48868539-90a62700-ede2-11e8-97ab-0e54aae1a038.png)

As you can see, when attributes are in place, icon is much smaller than expected size. Also, removal of width/height doesn't seem to have any negative effect (I've checked usage in HTML and CSS).

I'd like to hear you thoughts on the matter.

**Comment by cascornelissen** [comment]
Hi @stasgavrylov, thanks for the detailed explanation! I’m currently travelling so I’m not in a postition to give a detailed comment but to quickly answer the points you make:

1. There’s currently no way to create a root `style` element, no. This could be specified in your regular CSS, no?
1. I’ll have to look into the width/height attributes on the `use` element, you’re free to clone, modify, test and submit a PR if you want to and we’ll be able to discuss this particular change further over there.

**Comment by stasgavrylov** [comment]
Unfortunately, CSS styles do not affect shadow-dom elements created when using SVG fragments, so it has to be inside `style` tag in the `svg` itself.
Tbh, I actually forgot to dig deeper. I hope I'll have time this week.

**Comment by cascornelissen** [comment]
I just re-read issue #36 again (which is about using SVG fragments from CSS as well), the solution we ended up using over there was to generate both a `symbol`, a `use`, and [a `view` element](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#spritegenerateview---false). The `view` element is added with just a `viewBox` and no `width`/`height` attributes, solving issue 2 and this setup doesn't (AFAIK) need the styles in the SVG either.

I've added an [example on fragments](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/master/examples/fragments) showing the setup, does that help you or are you still running into issues then?

**Comment by cascornelissen** [comment]
Ping @stasgavrylov

**Comment by stasgavrylov** [comment]
I am sorry, I can't check this right now, but I will on Monday, and I'll get to you.

**Comment by cascornelissen** [comment]
No problem at all 😄  Thanks for the update!

**Comment by stasgavrylov** [comment]
@cascornelissen finally managed to test your approach. 
Thank you, fragments work great! I'm closing the issue.
