### ISSUE TITLE
SVGs with missing width, height and viewbox cause errors

### ISSUE THREAD

**Issue by roelofr** [cascornelissen/svg-spritemap-webpack-plugin#62]
If you try to add an SVG file without a `width`, `height` and `viewBox` element, the script returns an error exactly where it should report the missing file.

The `file` variable is used in a previous Promise function, but is no longer available (since the code has gone to a new `then` node).

I might write a PR for this, but don't have the time right now.

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/93b68de6d99975c01945816eea8c7d858ac7ead6/lib/generate-svg.js#L131

A hotfix is to replace this line with a `return;` statement, but it's not helping anyone solve the issue.

**Comment by cascornelissen** [comment]
Thanks for the issue, looks like I broke something while refactoring... It's been fixed in master, could you test it by installing the current master branch and let me know if it's resolved? Then I'll release a patch version with the fix ASAP.

```
npm install --save-dev cascornelissen/svg-spritemap-webpack-plugin
```

**Comment by cascornelissen** [comment]
ping @roelofr

**Comment by roelofr** [comment]
Sorry @cascornelissen for the delay, the project I was using it in had taken a sharp turn when I spent too much time figuring this out.

I re-tried it in a different project (@gumbo-millennium/) and added this invalid SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
    <path fill="red" d="M0 0h64v64H0z"/>
</svg>
```

The result looks promising:

```
Error: Invalid SVG '/home/roelof/dev/gumbo/resources/assets/icons/square.svg'; it's lacking both a
 viewBox and width/height attributes...
``

**Comment by cascornelissen** [comment]
No problem at all, thanks for the feedback. The fix has been released as part of [`3.2.1`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.2.1).

**Comment by alpezed** [comment]
I am using the latest version 3.5.3 but i still got this error.

**Comment by cascornelissen** [comment]
@alpezed, can you share an SVG that's throwing this error for you?

**Comment by alpezed** [comment]
Hi @cascornelissen  Here's one of the SVG that throwing this error

`<svg id="svg-source" height="0" version="1.1" 
  xmlns="http://www.w3.org/2000/svg" style="position:absolute; margin-left: -100%" 
  xmlns:xlink="http://www.w3.org/1999/xlink"><g xmlns="http://www.w3.org/2000/svg" id="alarm-clock" >
    <g>
      <path d="M30.156,10.025c2.29-2.289,2.29-6.016,0-8.311c-2.29-2.288-6.017-2.285-8.31,0
		c-0.172,0.175-0.169,0.416-0.076,0.625c-1.772-0.758-3.722-1.182-5.768-1.182c-2.048,0-3.998,0.424-5.772,1.182
		c0.094-0.209,0.094-0.449-0.077-0.62c-2.29-2.29-6.015-2.289-8.309,0c-2.291,2.292-2.291,6.02,0,8.31
		c0.11,0.111,0.257,0.167,0.402,0.167c0.078,0,0.144-0.057,0.214-0.089c-0.757,1.771-1.179,3.72-1.179,5.765
		c0,4.776,2.299,9.017,5.835,11.709c-0.446,0.189-0.853,0.478-1.098,0.908c-0.313,0.538-0.397,1.167-0.239,1.77
		c0.163,0.604,0.55,1.11,1.095,1.427c0.356,0.204,0.758,0.312,1.168,0.312c0.834,0,1.613-0.449,2.028-1.172
		c0.248-0.433,0.302-0.91,0.257-1.375c1.747,0.734,3.664,1.141,5.675,1.141c2.008,0,3.922-0.406,5.667-1.137
		c-0.044,0.462,0.011,0.939,0.262,1.374C22.348,31.552,23.124,32,23.954,32c0.408,0,0.814-0.11,1.168-0.314
		c0.542-0.312,0.932-0.814,1.092-1.418c0.164-0.605,0.082-1.236-0.231-1.777c-0.247-0.429-0.656-0.716-1.1-0.908
		c3.536-2.689,5.835-6.932,5.835-11.71c0-2.046-0.425-3.997-1.182-5.77c0.07,0.03,0.136,0.089,0.218,0.089
		C29.897,10.191,30.045,10.137,30.156,10.025z M2.651,2.526c1.848-1.841,4.853-1.841,6.695,0C9.421,2.6,9.519,2.613,9.614,2.639
		C6.628,4.084,4.208,6.503,2.762,9.49c-0.025-0.096-0.036-0.195-0.11-0.269C0.808,7.38,0.808,4.375,2.651,2.526z M9.08,30.259
		c-0.313,0.549-1.079,0.761-1.632,0.437c-0.279-0.162-0.479-0.422-0.562-0.73c-0.083-0.307-0.039-0.628,0.121-0.905
		c0.213-0.368,0.61-0.599,1.036-0.599c0.209,0,0.415,0.057,0.6,0.163C9.214,28.952,9.409,29.688,9.08,30.259z M24.991,29.062
		c0.161,0.274,0.205,0.6,0.12,0.906c-0.081,0.308-0.28,0.566-0.558,0.727c-0.559,0.324-1.315,0.113-1.634-0.437
		c-0.33-0.571-0.131-1.306,0.438-1.635c0.18-0.104,0.387-0.162,0.593-0.162C24.382,28.462,24.779,28.693,24.991,29.062z
		 M29.574,15.872c0,7.487-6.089,13.578-13.571,13.578c-7.486,0-13.577-6.091-13.577-13.578c0-7.482,6.091-13.571,13.577-13.571
		C23.485,2.301,29.574,8.39,29.574,15.872z M29.351,9.217c-0.076,0.074-0.087,0.174-0.111,0.268
		c-1.449-2.982-3.869-5.401-6.854-6.848c0.096-0.025,0.193-0.038,0.268-0.113c1.848-1.842,4.852-1.842,6.697,0
		C31.191,4.37,31.191,7.375,29.351,9.217z"/>
      <path d="M16.003,4.886c-6.114,0-11.086,4.971-11.086,11.083s4.972,11.084,11.086,11.084
		c6.111,0,11.08-4.972,11.08-11.084S22.114,4.886,16.003,4.886z M16.003,25.91c-5.485,0-9.943-4.461-9.943-9.941
		s4.458-9.94,9.943-9.94c5.479,0,9.939,4.46,9.939,9.94S21.481,25.91,16.003,25.91z"/>
      <path d="M16.573,15.775V8.992c0-0.316-0.255-0.572-0.57-0.572c-0.317,0-0.572,0.256-0.572,0.572v7.02
		c0,0.15,0.061,0.297,0.169,0.402l3.307,3.31c0.108,0.11,0.256,0.166,0.403,0.166c0.146,0,0.291-0.056,0.405-0.166
		c0.221-0.224,0.221-0.587,0-0.81L16.573,15.775z"/>
    </g>
  </g></svg>`

**Comment by cascornelissen** [comment]
@alpezed, in your case the error makes sense because the SVG you posted only has a `height` attribute (with a value of `0` even) so the plugin can't determine the actual size of the SVG which is needed for the spritemap.

Either add correct `height` **and** `width` attributes or set a correct `viewBox` attribute yourself.

**Comment by alpezed** [comment]
@cascornelissen  To give you an idea what i am doing, i am working a plugin for wordpress and these plugin has a lists of icons that compress in **.zip** file and when activated the plugin it will automatically extracted all the icons to svg file so don't need to edit each svg file to add correct size.

**Comment by cascornelissen** [comment]
@alpezed, I'm not 100% I understand but the `svg-spritemap-webpack-plugin` needs to know the height and width of each SVG that you want to end up in the spritemap. Without knowing the width/height of an SVG file it can't calculate where the file should be placed in the generated spritemap.
