### ISSUE TITLE
Laravel Mix Error: ValidationError: "src" is not allowed.

### ISSUE THREAD

**Issue by jedybeavis** [cascornelissen/svg-spritemap-webpack-plugin#63]
**─┬ laravel-mix@4.0.14
  └── webpack@4.29.3**

```
const mix = require('laravel-mix');
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');

// Set up the spritemap plugin
mix.webpackConfig({
    plugins: [
        new SVGSpritemapPlugin({
            src:'assets/svg/icons/*.svg',
            filename: '/svg/icons.svg',
            prefix: '',
            svg4everybody: true,
            svgo: {
                removeTitle: true,
                removeStyleElement: true,
                cleanupNumericValue: true,
            },
        })
    ]
});

// Adapt laravel-mix webpack config to better handle svg images.
Mix.listen('configReady', (webpackConfig) => {

    // Add separate svg loader
    webpackConfig.module.rules.push({
        test: /\.(svg)$/,
        include: /assets\/svg/,
        loaders: [
            {
                loader: 'file-loader',
                options: {
                    name: 'svg/[name].[ext]?[hash]',
                    publicPath: Config.resourceRoot
                }
            },

            {
                loader: 'img-loader',
                options: Config.imgLoaderOptions
            }
        ]
    });

    // Exclude local 'svg' folder from font loader
    let fontLoaderConfig = webpackConfig.module.rules.find(rule => String(rule.test) === String(/\.(woff2?|ttf|eot|svg|otf)$/))
    fontLoaderConfig.exclude = /(assets\/svg)/;

});
```

**Error: ValidationError: "src" is not allowed. "filename" is not allowed. "prefix" is not allowed. "svg4everybody" is not allowed. "svgo" is not allowed**

**Comment by cascornelissen** [comment]
Looks like you're using the old configuration setup with version `^3.0.0`, in which the configuration object was overhauled?

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.0.0
https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/v3.0.0/docs/options.md

**Comment by jedybeavis** [comment]
Thanks!

**Comment by arubacao** [comment]
@jedybeavis could you share an updated configuration?
`mix.version()` doesn't get along with this package.
`Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`

**Comment by schellenbergk** [comment]
Same here, `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`

**Comment by ziqq** [comment]
I have the same problem, Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'

**Comment by ziqq** [comment]
> @jedybeavis could you share an updated configuration?
> `mix.version()` doesn't get along with this package.
> `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`



> Same here, `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`

I found one of the solutions. We have to add this options 
`output: {
     chunk: {
                      keep: true
                 }
     },`

**Comment by MGMonge** [comment]
> > @jedybeavis could you share an updated configuration?
> > `mix.version()` doesn't get along with this package.
> > `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`
> 
> > Same here, `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`
> 
> I found one of the solutions. We have to add this options
> `output: { chunk: { keep: true } },`

Ohhh @ziqq thank you very much!!! I was getting crazy with this issue!!!

**Comment by mco67** [comment]
> > @jedybeavis could you share an updated configuration?
> > `mix.version()` doesn't get along with this package.
> > `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`
> 
> > Same here, `Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'`
> 
> I found one of the solutions. We have to add this options
> `output: { chunk: { keep: true } },`

Thx @ziqq You save my day !!!
