### ISSUE TITLE
Sprite prefix option to allow a function

### ISSUE THREAD

**Issue by danew** [cascornelissen/svg-spritemap-webpack-plugin#67]
Currently this plugin supports using globs to select SVGs from nested folder structures, which is awesome! 
It would be great to allow the `sprite.prefix` option to accept a function which can take the glob as an argument and produce a dynamic prefix, which would be helpful for nested folder structures.

Example assets:   
```
assets/
    - banners/
        - home.svg
        - contact.svg
    - logos/
        - black.svg
        - white.svg
```
Glob transformer
```js
const prefix = (glob) => {
	const parts = glob.split('/');
	return parts.splice(1, parts.length - 2).join('-')
};
```
Options:
```
{
    ...
    sprite: {
         prefix,
    },
    ...
}
```
Produces:   
```html
spritemap.svg#banners-home
spritemap.svg#banners-contact
spritemap.svg#logos-black
spritemap.svg#logos-white
```

**Comment by cascornelissen** [comment]
Sounds like what’s been started on in #61, right? You’re free to work on that further, I’m really busy the next couple of weeks unfortunately.

**Comment by danew** [comment]
Completely. 
Sorry for the duplicate ticket, I obviously didn't look hard enough for it.
