### ISSUE TITLE
Warning about "Variables are not supported when using CSS" when not using variables

### ISSUE THREAD

**Issue by illepic** [cascornelissen/svg-spritemap-webpack-plugin#71]
Config of:

```js
plugins: [
  new SVGSpritemapPlugin(
    path.resolve(./svgicon/svg/**/*.svg'),
    {
      styles: {
        filename: 'icons.css',
      },
      output: {
        svg4everybody: true,
        svgo: true,
      },
    }
  ),
],
```

results in command line output of:

```
WARNING in svg-spritemap-webpack-plugin
Variables are not supported when using CSS
```

**Comment by cascornelissen** [comment]
Do any of your sprites contain the [custom variable notation](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/variables.md) that this plugin supports? That (in combination withe the `styles.filename` option endinng in `.css` would throw this warning.

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/0716f25d71f11f4d988544d515d0357bca2cedbf/lib/index.js#L156-L158

If not could you `console.log()` the output of `findVariables(spritemap)` inside the `if` statement?

**Comment by illepic** [comment]
There it is! Thank you!

We're converting from Sass to PostCSS and experimenting with icon approaches in pure PostCSS. Really want to still leverage svg-spritemap-webpack-plugin, if possible!
