### ISSUE TITLE
Please add support for .pcss

### ISSUE THREAD

**Issue by nikkijd** [cascornelissen/svg-spritemap-webpack-plugin#73]

**Comment by cascornelissen** [comment]
I'm not exactly sure what you're looking for? You're always free to submit a PR, if you're talking about adding an additional supported extension for the [`styles.filename` option](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#stylesfilename--spritescss) a good place to start would be https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/master/lib/style-formatters.
