### ISSUE TITLE
package joi is deprecated, use @hapi/joi instead

### ISSUE THREAD

**Issue by Shne** [cascornelissen/svg-spritemap-webpack-plugin#78]
Looking at the dependencies at https://www.npmjs.com/package/svg-spritemap-webpack-plugin I clicked the joi link to https://www.npmjs.com/package/joi and found a disclaimer at the top saying 
`This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.`

So i'm guessing the line https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/b8b7185baa33720da93531069753cb00144b0bd8/package.json#L47 should be updated to target `@hapi/joi`. Assuming it is a required dependency being used.

It seems `@hapi/joi` has also been updated to version 15.

**Comment by cascornelissen** [comment]
Thanks for the heads-up, I totally missed this the last time I updated the dependencies... I've changed `joi` to `@hapi/joi` and released version [`3.3.4`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v3.3.4) 🚀

**Comment by Andreas-Halemba** [comment]
@cascornelissen funny that they seem to now are back at `joi`. Would you mind switching back to joi instead of `@hapi/joi`?

**Comment by cascornelissen** [comment]
@Andreas-Halemba, thanks for the heads-up. I've switched back to `joi` in bcc7f51, will be included in the next release whenever that will take place ✌🏼
