### ISSUE TITLE
Gradient as default color not working

### ISSUE THREAD

**Issue by vladislav-netkata** [cascornelissen/svg-spritemap-webpack-plugin#80]
Hi. I found 1 bug where I want to use "linearGradient" as default color. I have an icon:
[instagram.txt](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/3339522/instagram.txt)
_Change .txt to .svg, because GitHub not accepted svg file type._

When I tried to use LinearGradient as default color like that: `var:outer.fill="url(#a)"` I propose this will changed to `fill="url(#a)"` and linked to the LinearGradient element with id `a`, but I get a `symbol` element without LinearGradient element e.g: 

`<symbol id="instagram" viewBox="0 0 551.034 551.034">
        <title>instagram</title>
        <path d="M386.878 0H164.156C73.64 0 0 73.64 0 164.156v222.722c0 90.516 73.64 164.156 164.156 164.156h222.722c90.516 0 164.156-73.64 164.156-164.156V164.156C551.033 73.64 477.393 0 386.878 0zM495.6 386.878c0 60.045-48.677 108.722-108.722 108.722H164.156c-60.045 0-108.722-48.677-108.722-108.722V164.156c0-60.046 48.677-108.722 108.722-108.722h222.722c60.045 0 108.722 48.676 108.722 108.722v222.722z"
              fill="url(#a)"/>
        <path d="M275.517 133C196.933 133 133 196.933 133 275.516s63.933 142.517 142.517 142.517S418.034 354.1 418.034 275.516 354.101 133 275.517 133zm0 229.6c-48.095 0-87.083-38.988-87.083-87.083s38.989-87.083 87.083-87.083c48.095 0 87.083 38.988 87.083 87.083 0 48.094-38.989 87.083-87.083 87.083z"
              fill="url(#b)"/>
        <circle cx="418.31" cy="134.07" r="34.15" fill="url(#c)"/>
    </symbol>`. 

Fill was linked to the gradient element, but this element was cropped from the SVG.
Also in sass file:

`$sprites: (
'instagram': "data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 551.034 551.034'%3e%3cpath d='M386.878 0H164.156C73.64 0 0 73.64 0 164.156v222.722c0 90.516 73.64 164.156 164.156 164.156h222.722c90.516 0 164.156-73.64 164.156-164.156V164.156C551.033 73.64 477.393 0 386.878 0zM495.6 386.878c0 60.045-48.677 108.722-108.722 108.722H164.156c-60.045 0-108.722-48.677-108.722-108.722V164.156c0-60.046 48.677-108.722 108.722-108.722h222.722c60.045 0 108.722 48.676 108.722 108.722v222.722z' fill='___outer___'/%3e%3cpath d='M275.517 133C196.933 133 133 196.933 133 275.516s63.933 142.517 142.517 142.517S418.034 354.1 418.034 275.516 354.101 133 275.517 133zm0 229.6c-48.095 0-87.083-38.988-87.083-87.083s38.989-87.083 87.083-87.083c48.095 0 87.083 38.988 87.083 87.083 0 48.094-38.989 87.083-87.083 87.083z' fill='___inner___'/%3e%3ccircle cx='418.31' cy='134.07' r='34.15' fill='___dot___'/%3e%3c/svg%3e"
);`.

`$variables: (
    'instagram': (
        'outer': 'url(#a)',
        'inner': 'url(#b)',
        'dot': 'url(#c)'
    )
);`

Also no LinearGradient element, but fill option was linked to the element with defined id.

**Comment by cascornelissen** [comment]
It looks like the variable setup is working correctly as the `var:outer.fill="url(#a)"` gets transformed into `fill="___outer___"` and `__outer__` has a (default) value of `'url(#a)'` in the `$variables` list.

Could you provide the entire plugin configuration object?  I'm guessing SVGO is stripping the `LinearGradient`s when they're not getting used so you could try and disable it by setting [`output.svgo`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#outputsvgo--true) to `false`.

**Comment by vladislav-netkata** [comment]
>  I'm guessing SVGO is stripping the LinearGradients when they're not getting used so you could try and disable it by setting output.svgo to false.

Yep. Disabling SVGO optimization solve the problem.

**Comment by vlad-zhurakovskyi-git** [comment]
@cascornelissen thank you, its solve my problems too!
