### ISSUE TITLE
vue-cli-service compiling time increase drastically when svg-spritemap-webpack-plugin is added

### ISSUE THREAD

**Issue by wal0x** [cascornelissen/svg-spritemap-webpack-plugin#85]
I am using webpack@4.28.4 on a VueJS 2.6.10 project, and "svg-spritemap-webpack-plugin": "3.3.7"
 My vue.config.js looks like : 
```
const SVGSpritemapPlugin = require("svg-spritemap-webpack-plugin");

module.exports = {
  devServer: {
    port: "8082"
  },
  configureWebpack: {
    plugins: [
      new SVGSpritemapPlugin()
    ]
  }
};
```
The compiling time was ~150ms before installing the plugin, after installation it went to ~8000ms. I've commented the line  ```new SVGSpritemapPlugin()``` and the compiling time went back to normal (around 150ms)

**Comment by cascornelissen** [comment]
Is it possible that the plugin is finding a lot of SVGs? What's the filesize like of the spritemap SVG that's generated?

**Comment by wal0x** [comment]
No I have only 2 SVGs, even when I have 0 svg still the same problem
```
DONE  Compiled successfully in 8348ms  15:59:35                                                 No type errors found
Version: typescript 3.5.3
Time: 1016ms

  App running at:
  - Local:   http://localhost:8082/
  - Network: http://172.20.0.14:8082/```

**Comment by cascornelissen** [comment]
> What's the filesize like of the spritemap SVG that's generated?

**Comment by wal0x** [comment]
With my 2 SVGs 5KB each the size of the spritemap is 44KB. (is it normal ?)
With my SVGs folder empty the size of the spritemap is 38KB.

**Comment by cascornelissen** [comment]
That's probably because it's matching more SVGs but I can't know for sure without a configuration object. You could open the spritemap SVG in an editor and check some id's of the `symbol`s, that might help finding the SVGs.

**Comment by wal0x** [comment]
I investigated the spritemap I found two ```symbol``` tags. I rendred the svg and "surprisingly" I found two diagrams I have never seen before and I have no idea where it come from. 
(5min later)...
I found the two SVGs in two dependencies in my node_modules.
How can I tell the plugin to look for SVGs only inside the svgs folder ?
My folder s tree is like this : 
|__node_modules
|__public
|__src
|__svgs
|__vue.config.js
|...
