### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by diverent2** [cascornelissen/svg-spritemap-webpack-plugin#86]
Hi there,

I would greatly appreciate if you could add a changelog to your project.
This would help me (and others) to quickly spot changes (including breaking changes) between different versions.

Here's a guide on how to do this: [keepachangelog.com](https://keepachangelog.com/en/1.0.0/) ^^

Right now I'm trying to understand what was added between `3.3.x` and `3.4.x` to see if I can safely update my dependencies.
Keeping a changelog could also help to reduce confusion like in #54.

Thank you :)

**Comment by diverent2** [comment]
Update: Just saw your [release page](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases).
So i'´s already there, just not where I was looking.
Would still appreciate a changelog though, you would just need to copy the information.

**Comment by cascornelissen** [comment]
As you've sigured out already; GitHub Releases are used for the changelog which quite a lot of projects use (e.g. [webpack](https://github.com/webpack/webpack)) and I don't feel like having to do the additional work is worth the effort as most people know of the GitHub releases feature. So unless more people are running into this issue I'll leave it as it is for now.

Besides that, this plugin uses [semver](https://semver.org/) for its versions so as long as there's no major version change there _shouldn't_ be any breaking changes. Also, check out a package like [`npm-upgrade`](http://npmjs.com/package/npm-upgrade) which will find the latest versions of dependencies including changelogs for you by itself.
