### ISSUE TITLE
Include spritemap svg via require

### ISSUE THREAD

**Issue by philippdieter** [cascornelissen/svg-spritemap-webpack-plugin#87]
I would like to use the plugin with html-loader which interpolates the given html files and parses image src attributes to a require to be handled by a loader again.

To be able to use the sprite this way there need to be a way to use the spritemap similar to the style files like
`require('svg-spritemap-webpack-plugin/sprites.svg');`

Is this possible in a way? I don't know webpack that good so maybe I am just on the wrong track, I would appreciate any help.

**Comment by cascornelissen** [comment]
I think that's currently not possible because the SVG can only be written to the webpack output directory. It might be possible to rewrite this logic and write the file somewhere else on disk but the problem is that a lot of stuff needs to happen near the end of the pipeline (e.g. optimizations) so the SVG won't be ready whenever the JS is getting compiled.

What reason are you looking to import the SVG in your JS though? Maybe there's another way to accomplish what you're trying to do.

**Comment by philippdieter** [comment]
My goals are having hashes in the assets filenames, having the spritemap as separate file and not loading the sprites via js but having the right link in the html file.

So something like
```
<svg>
  <use xlink:href="~svg-spritemap-webpack-plugin/sprites.svg#sprite-house"></use>
</svg>
```
I would like to become something like
```
<svg>
<use xlink:href="assets/spritemap.f1c7a4abce1fcfb7808017dfa429ce48.svg#sprite-house"></use>
</svg>
```


As html-loader interpolates the input files by tag/attribute pairs this:
```
<img src="~images/logo.png" />
```
gets translated to ```require("~images/logo.png")``` and results in the hashed filename the loader config generates.

And I would be super happy if I could use the same scheme for the spritemap.
I tried different ways to solve this without asking but at some point or another my knowledge about the internal processes of webpack are to limited.

**Comment by cascornelissen** [comment]
I have two questions then:

1. Aren't you able to use something like [`html-webpack-plugin`]?(https://www.npmjs.com/package/html-webpack-plugin)
1. How do you load your CSS and JS then? Does it go through Webpack? Do you use something like Sass/Less/Stylus that needs compiling?

**Comment by philippdieter** [comment]
1: I use exactly this plugin. I saw the example how to include the spritemap into the page but I could not work out how to keep the svg in a separate file. I will use this option if there is no other way but I would prefer to have svg file to be able to cache it.
2: My goal is to have everything going through webpack. JS is included and processed with babel, pug generates my html files and sass for css.

**Comment by cascornelissen** [comment]
Alright, continuing on the second point. How do you load your CSS? Via a `require()` call or does the `html-webpack-plugin` take care of this for you? If so, do you have a custom template you're using for `html-webpack-plugin`?

**Comment by philippdieter** [comment]
I am sorry, completely missed your answer. But thank you for your help so far.

So I include css via require. I am not using a custom template, it's the default one.

**Comment by cascornelissen** [comment]
If your goal is to get everything through Webpack but still use filenames with hashes I'm not sure how that would work without using a custom template. Are you using something like React or Angular instead of "plain old" HTML?

**Comment by philippdieter** [comment]
I stripped down a frontend project to a minimal example:
https://github.com/philippdieter/frontend-example
I hope this works better than explaining my setup manually. 
Some times I use vue, but it would be nice to have a solution for plain old HTML.

**Comment by cascornelissen** [comment]
The provided example doesn't really help me with helping you because I still have no idea on how you're planning to use a specific sprite in your code... Let's say you have an icon you'd like to use in your UI, in what way would you like to insert that icon somewhere on your page?

**Comment by philippdieter** [comment]
I have the feeling I am missing some point, sorry...
I don't know what to add to what I have written in https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/87#issuecomment-518304330

Maybe you can give me a hint how the plugin was supposed to be used? How should the right spritemap file been found if it has a hash in its name?

**Comment by cascornelissen** [comment]
I'm afraid that's the catch 22 here, it can be used in different ways but it all depends on where you want to reference a sprite from. For example, you could...

- Use it in combination with the `html-webpack-plugin` like in the [`inline-html`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/master/examples/inline-html) example to include the entire SVG,
- Use it in combination with `webpack-stats-plugin` to write the output stats to a JSON file and write a helper that renders a SVG element in your templating language based on the value in the JSON file.
- Use pure JS to the same as the point above, fetching the JSON file and replacing elements in the page with the response.

In the end, unless you're using the first option I'm guessing you need to write some logic yourself that gets the filename (including hashes) from the stats JSON and using that value in your code.

**Comment by philippdieter** [comment]
So thank you very much for your time (and this plugin!), at least I know I didn't simply missed an option which magically resolves my problem. I will try to implement the second solution in some way.
