### ISSUE TITLE
mix.version() doesn't get along with this package.

### ISSUE THREAD

**Issue by ziqq** [cascornelissen/svg-spritemap-webpack-plugin#88]
Error: ENOENT: no such file or directory, open 'xyz\spritemap.js'

**Comment by cascornelissen** [comment]
Are you able to provide a **minimal** repository with code that reproduces this error for me?

**Comment by ziqq** [comment]
> Are you able to provide a **minimal** repository with code that reproduces this error for me?

https://github.com/ziqq/svg_sprite_map_plugin_error

**Comment by ziqq** [comment]
I found one of the solutions. We have to add this options 
`output: {
     chunk: {
                      keep: true
                 }
     },`

**Comment by cascornelissen** [comment]
Looking at the provided example and the fix you've found out about this makes sense. Laravel Mix seems to be doing something with the chunk (the generated .js file, which is mostly empty) after the files are emitted and this is exactly what the `output.chunk.keep` option is there for.
