### ISSUE TITLE
Error: ValidationError: "value" must be an object

### ISSUE THREAD

**Issue by simplenotezy** [cascornelissen/svg-spritemap-webpack-plugin#91]
I followed the guide, and I am getting error `Error: ValidationError: "value" must be an object`.

Heres my code:

      module.exports = {
        plugins: [
          new ImageminPlugin({
            optipng: { optimizationLevel: 2 },
            gifsicle: { optimizationLevel: 3 },
            pngquant: { quality: '65-90', speed: 4 },
            svgo: null,
            plugins: [imageminMozjpeg({ quality: 75 })],
            disable: (config.enabled.watcher),
          }),
          new UglifyJsPlugin({
            uglifyOptions: {
              ecma: 5,
              compress: {
                warnings: true,
                drop_console: true,
              },
            },
          }),
          new SVGSpritemapPlugin([
            "/images/svg/flags/48/*.svg"
          ])
        ],
      };

What's wrong here?

**Comment by cascornelissen** [comment]
Which version of the plugin are you using and can you confirm error also occurs when the `SVGSpritemapPlugin` is the only plug-in?
