### ISSUE TITLE
I'm getting the same error like Cannot read property 'entryOption' of undefined

### ISSUE THREAD

**Issue by dhivya-picco** [cascornelissen/svg-spritemap-webpack-plugin#92]
How can i fix this?

**Comment by cascornelissen** [comment]
What versions of the plugin and webpack are you using?

**Comment by dhivya-picco** [comment]
Thanks for your response.I just remove all the node modules and again i
have installed npm. Now It's working fine.



Regards,
DHIVYA NAGARAJAN

**Comment by cascornelissen** [comment]
Great to hear, thanks for letting me know!
