### ISSUE TITLE
Please any configuration to work with Nuxt.js?

### ISSUE THREAD

**Issue by sornss** [cascornelissen/svg-spritemap-webpack-plugin#94]
I'm trying the plugin with Nuxt.js 2.11.0 with the provided configuration but cannot get it to generate the result output filename.

Please any configuration to work with Nuxt.js?

Thank you.

```

// nuxt.config.js
import SVGSpritemapPlugin from 'svg-spritemap-webpack-plugin'

import build: {
    plugins: [
      new SVGSpritemapPlugin([
        '@/assets/svg/*.svg'
      ],
      {
        output: {
          filename: '@/static/svg/icons.svg',
          chunk: {
            keep: false
          }
        },
        sprite: {
          prefix: 'icon-'
        }
      })
    ],
...

```

**Comment by cascornelissen** [comment]
Since I haven't used Nuxt.js I can't be 100% sure but the `nuxt.config.js` looks like a custom variant of a `webpack.config.js`...

Could it be the `@` in the globs and the `output.filename` option?

If that's not it, does a file get generated (without setting the `output.filename` option)? If so, is it empty?

You're free to provide a **small** repository that reproduces your problem.

**Comment by sornss** [comment]
@cascornelissen, I have tried to change the `@` to `./` or `~/` without success. And it does not  generate a file even without the `output.filename`.

A repo has been set up at https://github.com/sornss/svg-spritemap-nuxtjs

Thanks again

**Comment by cascornelissen** [comment]
Thanks for the repo, it does seem to generate a file for me at `.nuxt/dist/client/spritemap.svg` with the only `.svg` file in the `./assets/svg/` directory when using `['./assets/svg/*.svg']` instead of `['@/assets/svg/*.svg']` as the first parameter?

**Comment by sornss** [comment]
My bad I did `npm run dev`.  With  `npm run build` or `npm run generate` when using `['./assets/svg/*.svg']`, it does generate the default spritemap.svg file that I can manually copy it and place to be used later at `./static/spritemap.svg` with `npm run dev`.

Thank you.
