### ISSUE TITLE
Custom output path

### ISSUE THREAD

**Issue by xavierfoucrier** [cascornelissen/svg-spritemap-webpack-plugin#95]
Hi!

I am trying to build a custom spritemap **using a different output path** as the webpack `output.path`: I didn't see any option in the package to edit the output path, but may be I am missing something...

Thanks for your answer :wink: 

> This is a duplicate of #10 I know, but I need to build svg sprite outside of the javascript default webpack path. Probably the `output.path` option should be the default value, but it would be easier if we can override this using the filename option.

**Comment by cascornelissen** [comment]
I don't think that's currently possible, maybe providing an absolute path to the [output.filename](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#outputfilename--spritemapsvg) option would work but I'm not sure.

What's the reason you need it to generate in a different place?

**Comment by xavierfoucrier** [comment]
Hi @cascornelissen,

Thanks for your reply.
I try and absolute path doesn't work.

In fact, I am working with another developer in a project that is not a full js app, and we need to have a specific folder structure:
- `javascript/src/*.js`: all js source files
- `picture/src/svg/*.svg`: all svg source files
- `styles/src/*.less|*.sass`: all style source files

The webpack build properly output each compiled assets in the appropriate folder:
- `javascript/app.min.js`
- `picture/sprite.min.svg`
- `styles/theme.min.css`

Anyway, I found a solution and use **a relative path**, the same way I do with `mini-css-extract-plugin.filename`: as the main `output.path` is set to the `javascript` folder, I am using `filename: ../picture/sprite.svg` to move to the right folder instead.

> Note that it does not work with webpack resolve aliases

Hope this should help someone in a similar situation :wink: 
I am closing the issue.
