### ISSUE TITLE
Generate .svg empty?

### ISSUE THREAD

**Issue by kareljan** [cascornelissen/svg-spritemap-webpack-plugin#96]
When I generate my sprite, the only content I get in the generated file is 
`<svg xmlns="http://www.w3.org/2000/svg"/>`

I made a simple test with just 1 file like this 
`new SVGSpritemapPlugin('test/delete.svg', {
             output: {
                    filename: 'icons/sprite.svg'
                }
})`
still no luck. Any ideas?

Thanks
Karel-Jan

**Comment by kareljan** [comment]
Never mind
It was an other plugin in my webpack that caused this.
Regards
Karel-Jan

**Comment by koenverburg** [comment]
Hi @kareljan,

we are also running into this issue, which plugin caused this at your end?

Best, Koen

**Comment by kareljan** [comment]
If I’m not mistaken, it was our cleanup plug-in that was cleaning a little too eager.
