### ISSUE TITLE
Few questions about config

### ISSUE THREAD

**Issue by VadymBoguslavsky** [cascornelissen/svg-spritemap-webpack-plugin#97]
Hi, i have few questions about config and other things: 
1. When i try to use svg or svgo or svg4everybode i have an error `Error: ValidationError: "svg" is not allowed` depending from package while compiling. i am using next js.
2. When i create sitemap.svg it have a symbol like

```
<svg xmlns="http://www.w3.org/2000/svg"><symbol id="sprite-drawer-close" viewBox="0 0 23 23"><title>drawer-close</title><defs><filter id="a" width="193.3%" height="193.3%" x="-46.7%" y="-33.3%" filterUnits="objectBoundingBox"><feOffset dy="2" in="SourceAlpha" result="shadowOffsetOuter1"/><feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="2"/><feColorMatrix in="shadowBlurOuter1" result="shadowMatrixOuter1" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.5 0"/><feMerge><feMergeNode in="shadowMatrixOuter1"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path fill="#FFF" d="M15 1.304L13.696 0 7.5 6.196 1.304 0 0 1.304 6.196 7.5 0 13.696 1.304 15 7.5 8.804 13.696 15 15 13.696 8.804 7.5z" filter="url(#a)" transform="translate(4 2)"/></symbol></svg>
```

 But when i add it to my css and in sources i can see that its just empty and i can't use it as `spritemap.svg#sprite-drawer-close`

my config is 

```
          config.plugins.push(
            new SVGSpritemapPlugin(['public/static/images/svg-gen/drawer-close.svg'], {
              styles: 'src/styles/_sprites.scss'
            })
          );
```

Thanks in advance.

**Comment by cascornelissen** [comment]
1. Please first read through https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/94, if that doesn't solve it for you, can you create a small repository that I can clone to debug this issue?
1. Can you show in which way you're using it in your CSS? And in which browser are you checking it?

**Comment by VadymBoguslavsky** [comment]
1. Yeah, it seems that something within project create this error, when i created rom a scretch its working without an error.
2. Using it just with ` background-image: url('./icons.svg'); `

**Comment by cascornelissen** [comment]
1. 👍 
1. That way you will be using the SVG directly instead of loading it through the spritemap, if you want to load it from the spritemap the notation should be something like below. There's more info in [this article from CSS Tricks](https://css-tricks.com/svg-symbol-good-choice-icons/)

   ```
   background-image: url('../path/to/spritemap.svg#name-of-sprite');
   ```

**Comment by VadymBoguslavsky** [comment]
I inserted this as first of my plugins and its working fine, but when trying to use it as css like 
`background-image: url('../path/to/spritemap.svg#name-of-sprite');`
the error is coming
`Invalid SVG '/icons.svg'; it's lacking both a viewBox and width/height attributes.`

But as i can see  in svg sprite i have a viewBox with some parameters like
`<svg xmlns="http://www.w3.org/2000/svg"><symbol id="icon-drawer-close" viewBox="0 0 23 23">`

**Comment by cascornelissen** [comment]
That warning is thrown by the plugin itself and means one of your source icons couldn't be parsed correctly:

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/ded5bb1ff2e7cdfa7c7ac66b0f5f0e4a4bcbfe89/lib/generate-svg.js#L153-L155

The root `<svg>` element should have either a valid `viewBox` attribute or a `width` and `height` attribute. Can you attach the file that's reference in the warning (`/icons.svg`)?

---

It could also be caused by the fact that the plugin generates the SVG for you and then when it runs again it is included in the list of source icons you've provided, essentially recursively including the spritemap output SVG.

**Comment by VadymBoguslavsky** [comment]
Yeah. You were right about the error, sorry)
But it seems that even if i try to set this as 
` background-image: url('/static/images/icons.svg#icon-drawer-close');` 
The svg do not shows up. Its empty. Attached sprite 
and config that i use now.

```
new SVGSpritemapPlugin(['./public/static/images/drawer/*svg'],
            {
              output: {
                filename: '@/static/svg/icons.svg',
                chunk: {
                  keep: false
                }
              },
              sprite: {
                prefix: 'icon-'
              },
              styles: true
            })
          )
```
[icons.svg.zip](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/4064597/icons.svg.zip)

**Comment by cascornelissen** [comment]
I can't really help you any further unless you provide a repo (or something similar) containing a minimal example of the way you're trying to use the plugin.
